# Generated by Django 4.0.5 on 2023-05-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftbooks',
            name='author_list',
        ),
        migrations.RemoveField(
            model_name='draftonline',
            name='author_list',
        ),
        migrations.RemoveField(
            model_name='draftpresentations',
            name='author_list',
        ),
        migrations.DeleteModel(
            name='DraftArticles',
        ),
        migrations.DeleteModel(
            name='DraftBooks',
        ),
        migrations.DeleteModel(
            name='DraftOnline',
        ),
        migrations.DeleteModel(
            name='DraftPresentations',
        ),
    ]
