# Generated by Django 4.0.5 on 2023-05-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_members_is_alumni_remove_members_is_faculty_and_more'),
        ('publication', '0002_remove_draftbooks_author_list_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublishedArticles',
            new_name='Articles',
        ),
        migrations.RenameModel(
            old_name='PublishedBooks',
            new_name='Books',
        ),
        migrations.RenameModel(
            old_name='PublishedOnline',
            new_name='Online',
        ),
        migrations.RenameModel(
            old_name='PublishedPresentations',
            new_name='Presentations',
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Articles', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Books', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='online',
            options={'verbose_name': 'Online', 'verbose_name_plural': 'Online'},
        ),
        migrations.AlterModelOptions(
            name='presentations',
            options={'verbose_name': 'Conference Presentations', 'verbose_name_plural': 'Conference Presentations'},
        ),
        migrations.AlterModelTable(
            name='articles',
            table='articles',
        ),
        migrations.AlterModelTable(
            name='books',
            table='books',
        ),
        migrations.AlterModelTable(
            name='online',
            table='online',
        ),
        migrations.AlterModelTable(
            name='presentations',
            table='presentations',
        ),
    ]
