# Generated by Django 4.0.5 on 2023-05-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_articles_creator_online_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='picture',
            field=models.ImageField(upload_to='publication/books/picture', verbose_name='Book Cover'),
        ),
    ]
