# Generated by Django 4.0.5 on 2023-05-23 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0004_remove_members_is_alumni_remove_members_is_faculty_and_more'),
        ('publication', '0006_alter_books_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='main_authors',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='other_authors',
        ),
        migrations.RemoveField(
            model_name='books',
            name='main_authors',
        ),
        migrations.RemoveField(
            model_name='books',
            name='other_authors',
        ),
        migrations.RemoveField(
            model_name='online',
            name='main_authors',
        ),
        migrations.RemoveField(
            model_name='online',
            name='other_authors',
        ),
        migrations.RemoveField(
            model_name='presentations',
            name='main_authors',
        ),
        migrations.RemoveField(
            model_name='presentations',
            name='other_authors',
        ),
        migrations.AddField(
            model_name='articles',
            name='co_editor',
            field=models.ManyToManyField(blank=True, null=True, related_name='article_co_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='books',
            name='co_editor',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_co_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='online',
            name='co_editor',
            field=models.ManyToManyField(blank=True, null=True, related_name='online_co_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presentations',
            name='co_editor',
            field=models.ManyToManyField(blank=True, null=True, related_name='presentation_co_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articles',
            name='author_list',
            field=models.ManyToManyField(related_name='article_author_list', to='members.members'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='books',
            name='author_list',
            field=models.ManyToManyField(related_name='book_author_list', to='members.members'),
        ),
        migrations.AlterField(
            model_name='books',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='online',
            name='author_list',
            field=models.ManyToManyField(related_name='online_author_list', to='members.members'),
        ),
        migrations.AlterField(
            model_name='online',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='author_list',
            field=models.ManyToManyField(related_name='presentation_author_list', to='members.members'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentation_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
