# Generated by Django 4.0.5 on 2023-05-23 00:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0007_remove_articles_main_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='co_editor',
            field=models.ManyToManyField(blank=True, related_name='article_co_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='books',
            name='co_editor',
            field=models.ManyToManyField(blank=True, related_name='book_co_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='online',
            name='co_editor',
            field=models.ManyToManyField(blank=True, related_name='online_co_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='co_editor',
            field=models.ManyToManyField(blank=True, related_name='presentation_co_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
