# Generated by Django 4.0.5 on 2022-07-16 16:46

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}', message='Personnel value must be number'), django.core.validators.MinLengthValidator(4, message='Ensure this value has at least 4 numbers')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='member/', verbose_name='Profile Picture')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('office_address', models.CharField(blank=True, max_length=200, null=True)),
                ('about_me', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default='True', verbose_name='Active')),
                ('is_faculty', models.BooleanField(verbose_name='Faculty')),
                ('is_staff', models.BooleanField(verbose_name='Staff')),
                ('is_graduate', models.BooleanField(verbose_name='Graduate Students')),
                ('is_undergrad', models.BooleanField(verbose_name='Undergraduate Students')),
                ('is_ra', models.BooleanField(verbose_name='Research Assistant')),
                ('is_postdocs', models.BooleanField(verbose_name='Postdoctoral Researcher')),
                ('is_alumni', models.BooleanField(verbose_name='Alumni')),
            ],
        ),
    ]
