# Generated by Django 4.0.5 on 2022-11-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'Members', 'verbose_name_plural': 'Members'},
        ),
        migrations.AddField(
            model_name='members',
            name='other',
            field=models.BooleanField(blank=True, null=True, verbose_name='Other'),
        ),
    ]
