# Generated by Django 4.0.5 on 2022-11-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_members_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='other',
            field=models.BooleanField(default='1', verbose_name='Other'),
        ),
    ]
