# Generated by Django 4.0.5 on 2022-07-13 19:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rural360DraftNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, verbose_name='username (The same as login username)')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('news_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('news_img', models.ImageField(upload_to='rural360/news/', verbose_name='news image')),
                ('statues', models.CharField(choices=[('0', 'in processing'), ('1', 'approved'), ('2', 'unapproved')], default='0', max_length=2)),
            ],
            options={
                'verbose_name': 'Rural360 draft news',
                'verbose_name_plural': 'Rural360 draft news',
                'db_table': 'rural360_draft_news',
            },
        ),
        migrations.CreateModel(
            name='Rural360PublishedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('news_type', models.CharField(default='rural360', max_length=20, verbose_name='news type')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('news_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('news_img', models.ImageField(upload_to='news/rural360', verbose_name='news image')),
                ('is_publish', models.BooleanField(default=True, verbose_name='publish')),
            ],
            options={
                'verbose_name': 'Rural360 published news',
                'verbose_name_plural': 'Rural360 published news',
                'db_table': 'rural360_published_news',
            },
        ),
        migrations.CreateModel(
            name='SixforsixDraftNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, verbose_name='username (The same as login username)')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('news_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('news_img', models.ImageField(upload_to='news/sixforsix', verbose_name='news image')),
                ('statues', models.CharField(choices=[('0', 'in processing'), ('1', 'approved'), ('2', 'unapproved')], default='0', max_length=2)),
            ],
            options={
                'verbose_name': '6for6 draft news',
                'verbose_name_plural': '6for6 draft news',
                'db_table': 'sixforsix_draft_news',
            },
        ),
        migrations.CreateModel(
            name='SixforsixPublishedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('news_type', models.CharField(default='sixforsix', max_length=20, verbose_name='news type')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('news_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('news_img', models.ImageField(upload_to='news/sixforsix', verbose_name='news image')),
                ('is_publish', models.BooleanField(default=True, verbose_name='publish')),
            ],
            options={
                'verbose_name': '6for6 published news',
                'verbose_name_plural': '6for6 published news',
                'db_table': 'sixforsix_published_news',
            },
        ),
        migrations.CreateModel(
            name='SurgeConDraftNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, verbose_name='username (The same as login username)')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('news_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('news_img', models.ImageField(upload_to='news/surgecon', verbose_name='news image')),
                ('statues', models.CharField(choices=[('0', 'in processing'), ('1', 'approved'), ('2', 'unapproved')], default='0', max_length=2)),
            ],
            options={
                'verbose_name': 'SurgeCon draft news',
                'verbose_name_plural': 'SurgeCon draft news',
                'db_table': 'surgecon_draft_news',
            },
        ),
        migrations.CreateModel(
            name='SurgeConPublishedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('news_type', models.CharField(default='surgecon', max_length=20, verbose_name='news type')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('news_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('news_img', models.ImageField(upload_to='news/surgecon', verbose_name='news image')),
                ('is_publish', models.BooleanField(default=True, verbose_name='publish')),
            ],
            options={
                'verbose_name': 'SurgeCon published news',
                'verbose_name_plural': 'SurgeCon published news',
                'db_table': 'surgecon_published_news',
            },
        ),
    ]
