# Generated by Django 4.0.5 on 2022-12-19 15:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=100, null=True, verbose_name='affiliation')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='external link')),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('news_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cover_img', models.ImageField(upload_to='news/', verbose_name='cover image')),
                ('is_publish', models.BooleanField(default=True, verbose_name='publish')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'db_table': 'news',
            },
        ),
        migrations.DeleteModel(
            name='Rural360DraftNews',
        ),
        migrations.DeleteModel(
            name='Rural360PublishedNews',
        ),
        migrations.DeleteModel(
            name='SixforsixDraftNews',
        ),
        migrations.DeleteModel(
            name='SixforsixPublishedNews',
        ),
        migrations.DeleteModel(
            name='SurgeConDraftNews',
        ),
        migrations.DeleteModel(
            name='SurgeConPublishedNews',
        ),
    ]
