# Generated by Django 4.0.5 on 2023-05-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_headline',
            field=models.BooleanField(default=False, verbose_name='headline'),
        ),
    ]
