# Generated by Django 4.0.5 on 2023-05-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_bottominfo_headlinenews_remove_news_is_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottominfo',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AlterField(
            model_name='bottominfo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
