# Generated by Django 4.0.5 on 2023-04-24 07:28

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('abstract', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('background', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('project_history', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='project history')),
                ('data_collection', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='data collection & analysis')),
                ('goal', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='goal & strategy')),
                ('audiences', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('impact', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='impact on community')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated date')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('RA', 'Requiring attention'), ('UR', 'Under Review'), ('PR', 'Post-Review'), ('WD', 'Withdrawn')], default='DR', max_length=2)),
                ('co_pi', models.ManyToManyField(blank=True, null=True, related_name='Co_PI', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pi', models.ManyToManyField(blank=True, null=True, related_name='PI', to=settings.AUTH_USER_MODEL)),
                ('referee', models.ManyToManyField(blank=True, null=True, related_name='Referee', to=settings.AUTH_USER_MODEL)),
                ('secretary', models.ManyToManyField(blank=True, null=True, related_name='Secretary', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ManyToManyField(blank=True, related_name='Supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('degree', models.CharField(blank=True, max_length=200, null=True, verbose_name='Education Degree')),
                ('position', models.CharField(blank=True, max_length=250, null=True)),
                ('role', models.CharField(blank=True, max_length=250, null=True, verbose_name='Role in this research')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='DOI')),
                ('url', models.URLField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=250, null=True, verbose_name='full reference')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250)),
                ('justification', models.CharField(blank=True, max_length=250, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='Appendices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('attachment', models.FileField(upload_to='proposal/')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposal')),
            ],
        ),
    ]
