# Generated by Django 4.0.5 on 2023-05-23 00:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='co_pi',
            field=models.ManyToManyField(blank=True, related_name='Co_PI', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pi',
            field=models.ManyToManyField(blank=True, related_name='PI', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='referee',
            field=models.ManyToManyField(blank=True, related_name='Referee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='secretary',
            field=models.ManyToManyField(blank=True, related_name='Secretary', to=settings.AUTH_USER_MODEL),
        ),
    ]
